"""Shared schema contract (X0.4, SSOT §7) + the codegen that keeps the JSON-Schema
snapshot and frontend TypeScript types in sync."""

from app.schemas.models import (
    ALL_MODELS,
    Board,
    CitationType,
    DailyDigest,
    ExtractionMethod,
    FrameAnnotation,
    IngestionResult,
    KnowledgeModule,
    KnowledgeNote,
    NormalizedSource,
    Origin,
    PipelineRun,
    Schema,
    SeenItem,
    Segment,
    Source,
    SourceFailure,
    SourceFailureKind,
    SourceRequest,
    SourceType,
    StepTrace,
    Subscription,
    SubscriptionFailureKind,
    Tier,
    TrackedItemCard,
    UsageEvent,
)

__all__ = [
    "ALL_MODELS",
    "Board",
    "CitationType",
    "DailyDigest",
    "ExtractionMethod",
    "FrameAnnotation",
    "IngestionResult",
    "KnowledgeModule",
    "KnowledgeNote",
    "NormalizedSource",
    "Origin",
    "PipelineRun",
    "Schema",
    "Segment",
    "SeenItem",
    "Source",
    "SourceFailure",
    "SourceFailureKind",
    "SourceRequest",
    "SourceType",
    "StepTrace",
    "Subscription",
    "SubscriptionFailureKind",
    "Tier",
    "TrackedItemCard",
    "UsageEvent",
]
